{% set name = "tornado" %}
{% set version = "6.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tornado-{{ version }}.tar.gz
  sha256: 4b927c4f19b71e627b13f3db2324e4ae660527143f9e1f2e2fb404f3a187e2ba

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - tornado
    - tornado.platform
    - tornado.test
    - tornado.gen
    - tornado.netutil

about:
  home: https://www.tornadoweb.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Python web framework and asynchronous networking library, originally developed at FriendFeed.
  description: |
    Tornado is a Python web framework and asynchronous networking library.
    By using non-blocking network I/O, Tornado can scale to tens of thousands
    of open connections, making it ideal for long polling, WebSockets, and
    other applications that require a long-lived connection to each user.
  doc_url: https://www.tornadoweb.org/en/stable/
  dev_url: https://github.com/tornadoweb/tornado

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
