{% set version = "5.0.2" %}

package:
  name: tornado
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tornado/tornado-{{ version }}.tar.gz
  sha256: 1b83d5c10550f2653380b4c77331d6f8850f287c4f67d7ce1e1c639d9222fbc7

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - futures              # [py<32]
    - singledispatch       # [py<34]
    - backports_abc >=0.4  # [py<35]

test:
  imports:
    - tornado
    - tornado.platform
    - tornado.test
    - tornado.gen
    - tornado.netutil

about:
  home: http://www.tornadoweb.org/
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  license_url: http://www.apache.org/licenses/LICENSE-2.0
  summary: 'A Python web framework and asynchronous networking library, originally developed at FriendFeed.'
  description: |
    Tornado is a Python web framework and asynchronous networking library.
    By using non-blocking network I/O, Tornado can scale to tens of thousands
    of open connections, making it ideal for long polling, WebSockets, and
    other applications that require a long-lived connection to each user.
  doc_url: http://www.tornadoweb.org/en/stable/
  doc_source_url: https://github.com/tornadoweb/tornado/blob/stable/docs/index.rst
  dev_url: https://github.com/tornadoweb/tornado

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
