{% set name = "tornado" %}
{% set version = "6.5.10" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tornado-{{ version }}.tar.gz
  sha256: a6b1ccd08c04b4a06fb5aeb381be99de5ad1e5375c1785e31d78c880feb57687

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
    # Upstream test suite is run via tornado.testing/unittest, not pytest.
    - python -bb -m tornado.test  # [not win]
    # Upstream disables fail-if-logs on Windows due to occasional platform-specific
    # log/stderr messages: https://github.com/tornadoweb/tornado/commit/734f397782e6d94ccc2ad83607d01cd3cd090839
    - python -bb -m tornado.test --fail-if-logs=false  # [win]
  imports:
    - tornado
    - tornado.platform
    - tornado.test
    # from test file imports
    - tornado
    - tornado.auth
    - tornado.autoreload
    - tornado.concurrent
    # requires pycurl
    #- tornado.curl_httpclient
    - tornado.escape
    - tornado.gen
    - tornado.http1connection
    - tornado.httpclient
    - tornado.httpserver
    - tornado.httputil
    - tornado.ioloop
    - tornado.iostream
    - tornado.locale
    - tornado.locks
    - tornado.log
    - tornado.netutil
    - tornado.options
    - tornado.platform.asyncio
    # requires pycares
    #- tornado.platform.caresresolver
    # requires twisted
    #- tornado.platform.twisted
    - tornado.process
    - tornado.queues
    - tornado.routing
    - tornado.simple_httpclient
    - tornado.tcpclient
    - tornado.tcpserver
    - tornado.template
    - tornado.test
    - tornado.test.httpclient_test
    - tornado.test.options_test
    - tornado.test.runtests
    - tornado.test.util
    - tornado.testing
    - tornado.util
    - tornado.web
    - tornado.websocket
    - tornado.wsgi

about:
  home: https://www.tornadoweb.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Python web framework and asynchronous networking library, originally developed at FriendFeed.
  description: |
    Tornado is a Python web framework and asynchronous networking library.
    By using non-blocking network I/O, Tornado can scale to tens of thousands
    of open connections, making it ideal for long polling, WebSockets, and
    other applications that require a long-lived connection to each user.
  doc_url: https://www.tornadoweb.org/en/stable/
  dev_url: https://github.com/tornadoweb/tornado

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
