{% set version = "4.5.1" %}

package:
  name: tornado
  version: {{ version }}

source:
  fn: tornado-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/t/tornado/tornado-{{ version }}.tar.gz
  sha256: db0904a28253cfe53e7dedc765c71596f3c53bb8a866ae50123320ec1a7b73fd

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - ordereddict          # [py<27]
    - ssl_match_hostname   # [py2k]
    - singledispatch       # [py<34]
    - certifi              # [py<34]
    - backports_abc >=0.4  # [py<35]

test:
  imports:
    - tornado
    - tornado.platform
    - tornado.test
    - tornado.gen
    - tornado.netutil

about:
  home: http://www.tornadoweb.org/
  license: Apache 2.0
  summary: 'Tornado is a Python web framework and asynchronous networking library, originally developed at FriendFeed.'

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
