{% set version = "5.0" %}

package:
  name: tornado
  version: {{ version }}

source:
  fn: tornado-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/t/tornado/tornado-{{ version }}.tar.gz
  sha256: 62f754562c61ea94b00d61727202105068bc2760f076cc34d2da1a57041731aa

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - ordereddict          # [py<27]
    - singledispatch       # [py<34]
    - backports_abc >=0.4  # [py<35]
    - futures              # [py2k]

test:
  imports:
    - tornado
    - tornado.platform
    - tornado.test
    - tornado.gen
    - tornado.netutil

about:
  home: http://www.tornadoweb.org/
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  license_url: http://www.apache.org/licenses/LICENSE-2.0
  summary: 'A Python web framework and asynchronous networking library, originally developed at FriendFeed.'
  description: |
    Tornado is a Python web framework and asynchronous networking library.
    By using non-blocking network I/O, Tornado can scale to tens of thousands
    of open connections, making it ideal for long polling, WebSockets, and
    other applications that require a long-lived connection to each user.
  doc_url: http://www.tornadoweb.org/en/stable/
  doc_source_url: https://github.com/tornadoweb/tornado/blob/stable/docs/index.rst
  dev_url: https://github.com/tornadoweb/tornado

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
