travis:
  secure:
    BINSTAR_TOKEN: fKE6ZAoTHhDA2ogX0Fd5VlXeTZ4zGTr9HHY5JWVp4nsPGlHvy4D67y6sI6AE+nuzsXmI4kxEh7FZQRJoip4bN9AH/JCBByBs3rzvR6w4erxGJCQw8aoaWL9qsjRqov1lxCBlx/QLHFC3KThLH5122XkBsOK4hDeqX175Krk497ldLxO7XFm9/uXakJlzWsIzyJK7croTX0HSOl/H7zqu+i7p1b1T1mlYVqTxdtz/TE0z+7oQZlRl865/SUnpvezumaOeqXnIlAnnOemJOM0qrNI1IjIQmBwR6p0iWTaEfxciq36XQWjnxduNjovjEpPAB+TToiJc3Ia5nUM9S0Np0E0UaV+GLwbPZkBYDq6NHyd6ktiP8jUnL69df1WYQQ+y3QU5PKD+JZDrCqnugDwmHvqHWJlROPxVIpDchNLpPdbwDL/9Bbkl6BOtV5ddt1fI2znn0Kt8sfMpcfclImi8L36CJbH1uW6ZIc66Im1DplguWzMvLK2GIvBfDoYL4J4hL14iiwa4nxPUpR8lGSKViRM6D39D555DvloiCPHVDRzMtOof58w60wFrjsJgZ8YoSibx6AF8BfbbTEjh+UyNwDGxJCBOFafI5b39JNcIz+W3cPxBoBIsOmaDaiS+ysOfnbM3yrxU8FQz6VA9jJVFcC6CujvjQaxBkw/tHAC0Idk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
